Feature/skeleton loader
TechneAi20231005/LatestSoftlaunchcode18versioncode pull request #170
Opened 2024-05-16 07:31 UTC by priyankatechneai

Card skeleton add in ConsolidatedView  master

2024-05-21 07:02 UTC, AmitSolnke requested changes
Kindly check the responsiveness from all aspects.
cards are overlapping on each other.

2024-05-22 04:30 UTC, priyankatechneai commented
resolved

2024-05-22 04:30 UTC, priyankatechneai commented
resolved

2024-05-22 07:13 UTC, somyaranjan-techneai commented on src/components/custom/loader/CardLoadingSkeleton.jsx
> +                    style={{ width: "80%", height: "20px" }}
Remove all inline styles, use bootstrap class or external style

2024-05-22 07:15 UTC, somyaranjan-techneai commented on src/screens/ConsolidatedView/ConsolidatedSlice.js
> +      state.isLoading.consolidatedDataList = false;
don't use unnecessary state, use existing state

2024-05-22 11:35 UTC, somyaranjan-techneai commented on src/screens/ConsolidatedView/CurrentClientProject.jsx
> +
Remove commented code, if not requard

2024-05-22 11:35 UTC, somyaranjan-techneai commented on src/screens/ConsolidatedView/CurrentClientProject.jsx
> +  useState(() => {}, []);
what is this

2024-05-23 06:32 UTC, priyankatechneai commented on src/components/custom/loader/CardLoadingSkeleton.jsx
> +                    style={{ width: "80%", height: "20px" }}
resolved

2024-05-23 06:34 UTC, priyankatechneai commented on src/screens/ConsolidatedView/ConsolidatedSlice.js
> +      state.isLoading.consolidatedDataList = false;
resolved

2024-05-23 06:34 UTC, priyankatechneai commented on src/screens/ConsolidatedView/CurrentClientProject.jsx
> +
resolved

2024-05-23 06:35 UTC, priyankatechneai commented on src/screens/ConsolidatedView/CurrentClientProject.jsx
> +  useState(() => {}, []);
resolved

2024-06-05 17:19 UTC, merged